### ISSUE TITLE
uncertainties fails on python 3.6

### ISSUE THREAD

**Issue by BishopWolf** [lebigot/uncertainties#106]
I have reported this bug [here](https://github.com/lmfit/lmfit-py/issues/605)

Basically, the issue is caused by literal python@2 strings not valid for python@3 representation in the uncertainties package, also there are a lot of python@2-isms like `iteritems` for arrays.

**Comment by lebigot** [comment]
The problem does not lie with the source code of `uncertainties` but [with the installation process](https://github.com/lmfit/lmfit-py/issues/605#issuecomment-555051284).

I am keeping this open, but fixing the problem should start with https://github.com/lmfit/lmfit-py/issues/605.

**Comment by BishopWolf** [comment]
You can follow the discussion on Slicer forum [here](https://discourse.slicer.org/t/problems-installing-lmfit-python-package/9210/4)

**Comment by BishopWolf** [comment]
I found [this](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/) read very useful and instructing

**Comment by lebigot** [comment]
[Version 3.1.3 now has a wheel](https://pypi.org/project/uncertainties/#files), which should help lmfit and other projects to easily install uncertainties for Python 3:

**Comment by lebigot** [comment]
I'm reopening this because version 3.1.3 was not getting installed properly on Python 2. I'll work on this later.

**Comment by BishopWolf** [comment]
The problem with [the test build](https://travis-ci.org/lebigot/uncertainties/jobs/616103980) is that you are still using eggs instead of wheels.

**Comment by jcfr** [comment]
Thanks for moving this forward :pray: 

> Version 3.1.3 now has a wheel,

In fact, wheels are expected to have the `.whl` extension 

You could look at this project for an example of project releasing wheels. See https://github.com/amueller/word_cloud

**Comment by lebigot** [comment]
The link to 3.1.3 (which I removed) pointed to version 3.1.2, which doesn't have any wheel. I removed the link in the messages above. The current GitHub version does have a wheel (for Python 3 at least). However, it doesn't install properly yet. I'll have another look.

**Comment by lebigot** [comment]
Version 3.1.4 on PyPI has universal wheels. Does this solve this issue?
