### ISSUE TITLE
Please be more specific on NumPy compatibility

### ISSUE THREAD

**Issue by jonasstein** [lebigot/uncertainties#115]
https://github.com/lebigot/uncertainties/blob/master/setup.py#L160

> - 3.1.2: Partial fix for NumPy 1.17 and ``unumpy.ulinalg.pinv()``.

What does this mean? Does NumPy 3.1.2 work with NumPy 1.17, or not?
Please be more specific on the dependencies, this will help distributing the package. Thank you very much.

**Comment by lebigot** [comment]
In terms of dependencies, all versions of NumPy should work.

uncertainties does not fully work _like_ NumPy 1.17. Namely, `unumpy.ulinalg.pinv()` [does not handle the extra `hermitian` argument](https://github.com/lebigot/uncertainties/blob/99d89d9047a638af92006b5c7f4606dc8bfd60b9/uncertainties/unumpy/core.py#L553) [added](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.pinv.html) to `pinv()` in NumPy 1.17.

I update the version info in [setup.py](https://github.com/lebigot/uncertainties/commit/597c0d58a787e3fb33c6bce425b261268993d459) so as to better address the dependency issue.
