### ISSUE TITLE
Missing git tags for 3.1.3/3.1.4

### ISSUE THREAD

**Issue by felixonmars** [lebigot/uncertainties#124]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by lebigot** [comment]
Good point, thanks.

I added a 3.1.4 tag and did an GitHub release.

Now, version 3.1.3 was broken and should not exist. It was removed from PyPI, and I guess has been removed from Anaconda. I am thinking that not tagging it is best. What do you think?

**Comment by felixonmars** [comment]
Thanks, I'm okay either way :)

**Comment by lebigot** [comment]
Great, thanks for the feedback.
