### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by mocquin** [lebigot/uncertainties#125]
In the doc at [https://pythonhosted.org/uncertainties/tech_guide.html#comparison-operators](https://pythonhosted.org/uncertainties/tech_guide.html#comparison-operators), I think there is a typo in the second prompt example. 
The current state is : 
```
>>> y = ufloat(3.14, 0.01)
>>> x != y
True
```
while I'd expect it to be : 
```
>>> y = ufloat(3.14, 0.01)
>>> x != y
False
```

**Comment by lebigot** [comment]
The published version is correct: two _independent_ random variables x and y are generally, such that x-y ≠ 0, so it is consistent to say that x ≠ y. 

Maybe this would require more explanation in the doc?

**Comment by mocquin** [comment]
My bad, I was reading "==" like the cell above, hence expected a False result. Closing this now.
Thanks !

**Comment by lebigot** [comment]
That's an interesting point, though. I am a believer in the principle of least surprise, so I switched to `==` in the latest version.
I also added the `x-y` explanation that I was mentioning earlier.

As a bonus, I realized that the examples are still in Python 2, so I opened a new issue on converting them to Python 3 (now that the source is more geared towards Python 3).
