### ISSUE TITLE
np.log(uarray) doesn't work

### ISSUE THREAD

**Issue by mariana-navia** [lebigot/uncertainties#132]
Hello!
I've been using the uncertainties package for about a month now and today I encontered an issue by trying to do this:

import numpy as np
from uncertainties import *
from uncertainties.umath import *
example = np.array([1,2,3])
uexample = unumpy.uarray([1,3,4],[1,1,1])
test = np.log(example)
utest = np.log(uexample)

when I run test it works fine, on the other hand, when I try printing utest, it gives me the following error:
'Variable' object has no attribute 'log'

How can I fix this?

**Comment by lebigot** [comment]
[The documentation](https://pythonhosted.org/uncertainties/numpy_guide.html#mathematical-functions) indicates that arrays with uncertainties must use the dedicated mathematical functions from `uncertainties.unumpy` (e.g. `from uncertainties import unumpy as un; utest = unp.log(uexample)`). 

Does this indeed solve your problem?

**Comment by mariana-navia** [comment]
> [The documentation](https://pythonhosted.org/uncertainties/numpy_guide.html#mathematical-functions) indicates that arrays with uncertainties must use the dedicated mathematical functions from `uncertainties.unumpy` (e.g. `from uncertainties import unumpy as unp; utest = unp.log(uexample)`).
> 
> Does this indeed solve your problem?

Yes!! Thank you very much :)
