### ISSUE TITLE
Cannot find reference 'ufloat' in 'uncertainties.py' 

### ISSUE THREAD

**Issue by itsmoritzz** [lebigot/uncertainties#139]
Hi,

after having installed the package using _pip install --upgrading uncertainties_, the error message given in the title shows up when hovering over ufloat from the import command _from uncertainties import ufloat_. I tried using the package both on Windows 10 and macOS Big Sur. What am I doing wrong?

Thanks for the help!

**Comment by lebigot** [comment]
I am guessing that you are using a specific code editor, since you mention "hovering"? Without this information, I'm not sure how to help yet.

**Comment by lebigot** [comment]
Can you elaborate, or should I assume that your problem is solved and close this issue?
