### ISSUE TITLE
 dependency on past generates warnings in Python 3 #145 

### ISSUE THREAD

**Issue by PhilReinhold** [lebigot/uncertainties#152]
Issue #145 was closed by the author but not addressed. The fix in #146 should be re-opened and applied.

**Comment by PeterKraus** [comment]
It would be great to have this addressed sooner or later. It's stopping me from running my test suite using `-Werror`, and as said in the original post, in `3.12` we'll be in trouble.

**Comment by sphuber** [comment]
@PeterKraus not sure how you are running your tests, but if you are using `pytest` (highly recommendable), you can filter this specific warning so you can still run with the option that turns warnings into errors I believe.

Of course this is a temporary work around and I also strongly believe this should be addressed. @lebigot is there any chance you can address this. Also more than happy to pitch in with the maintenance of the package if needed.

**Comment by lebigot** [comment]
Thanks for the ping. Fixed in version 3.1.7.
