### ISSUE TITLE
UFloat from a sequence (of measurements) 

### ISSUE THREAD

**Issue by arian-f** [lebigot/uncertainties#154]
I often have a sequence of measurements of the same sample with the same measurement device. Every single measurement has an uncertainty that is unacceptably high, which is one reason for the repeated measurement. For this I have this function:

```python

import numpy
from typing import Iterable

def uquantity(x: Iterable) -> UFloat:
    '''for a repeated measurement of the quantity `x`, return ufloat(nanmean(x), nanstd(x))'''
    x = tuple(x)
    return ufloat(numpy.nanmean(x), numpy.nanstd(x)) 
```

Do you think it would be worthwhile to include it in the uncertainties package directly?

Of course it's almost trivial and clearly only a convenience thing to have this. However I feel it's pretty common, probably enough to include it in uncertainties directly.

**Comment by lebigot** [comment]
Thanks for the suggestion.

While people who do repeated measurements would probably implement something like this, I believe that this use case is in itself not common enough to warrant including such a function in the module.

I'm thinking that you'd want to create your own library, for this common use case of yours.
