### ISSUE TITLE
Error for 'Variable' object has no attribute 'strip' and Affinf function can't convert.

### ISSUE THREAD

**Issue by gittyhub2018** [lebigot/uncertainties#165]
Hello,

i'm new to this package and i read the how-to from the uncertainties package repo. I want to calculate the uncertainties for my signal chain. But python with spyder IDE throw an error and i don't find the mistake.  I use follow code:
```
import uncertainties as un
import matplotlib.pyplot as plt

S=1*10**(-6)  #Sensitivity from Sensor
EQ=un.ufloat(1000.0,0.005) #Heat flux with 0.55% uncertainty
G1=1+(50000/10) #Gain for instrumentation amplifier
G=un.ufloat(G1,0.01) #Gain with Gain Error
Gi=1+(50000/10) #ideal Gain
EUo=un.ufloat(EQ,0.0001)
UoD=un.ufloat(G,0.000002) #Spannungsoffsetdrift
Ge=un.ufloat(G,0.000005) #Lineare Regression von Excel mit R²=0,9988 und vier Stützpunkten. Gain Error.
EA=Ge+UoD+un.ufloat(G,0.000001) #Error summation
Ur=S*EUo #simulated error without amplification
Go=un.ufloat(G.nominal_value,EA) #real amplification
Ug=Ur*Go #Signal with errors
Ui=S*EQ*Gi #Signal without errors

#Plot
plt.plot(Ug,Ui)
plt.title("real vs. ideal")
plt.xlabel('Voltage1[V]')
plt.ylabel('Voltage2[V]')
plt.show()
```

And follow error occure (File path was shorten with "..."):

> Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 7.34.0 -- An enhanced Interactive Python.
> 
> runfile('.../test.py', wdir='...')
> Traceback (most recent call last):
> 
>   File "...\Python\Python310\lib\site-packages\uncertainties\core.py", line 3297, in ufloat
>     return Variable(nominal_value, std_dev, tag=tag)
> 
>   File "....\Python\Python310\lib\site-packages\uncertainties\core.py", line 2766, in __init__
>     value = float(value)
> 
>   File "...\Python\Python310\lib\site-packages\uncertainties\core.py", line 2714, in raise_error
>     raise TypeError("can't convert an affine function (%s)"
> 
> TypeError: can't convert an affine function (<class 'uncertainties.core.Variable'>) to float; use x.nominal_value
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "...\Python\Python310\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
>     exec(code, globals, locals)
> 
>   File "...\test.py", line 15, in <module>
>     EUo=un.ufloat(EQ,0.0001)
> 
>   File "...\Python\Python310\lib\site-packages\uncertainties\core.py", line 3310, in ufloat
>     final_ufloat = ufloat_obsolete(nominal_value, tag_arg)
> 
>   File "...\Python310\lib\site-packages\uncertainties\core.py", line 3253, in ufloat_obsolete
>     return ufloat_fromstr(representation, tag)
> 
>   File "...Python310\lib\site-packages\uncertainties\core.py", line 3237, in ufloat_fromstr
>     representation.strip())
> 
> AttributeError: 'Variable' object has no attribute 'strip'<
> 

Can anyone tell me, where is my mistake?

Thank you for your help.

Sincerely yours,

gittyhub2018

**Comment by lebigot** [comment]
So, starting from where the error comes from (`EUo=un.ufloat(EQ,0.0001)`) and looking at the documentation, you see that `EQ` should be a _float_, not a number with uncertainty.

What did you intend to do? Something like EUo = EQ ± 0.0001? If this is the case, you simply do `EUo = EQ + un.ufloat(0, 0.0001)`.

Side note: in `EQ=un.ufloat(1000.0,0.005) #Heat flux with 0.55% uncertainty`, a 0.55 % uncertainty would be EQ = 1000 ± 5.5.

**Comment by gittyhub2018** [comment]
Thank you for your help. This was the idea. Thank you. 

I have only a second question: Do you know a chance to access the output via another python package?
I want use matplotlib with error bars for show my calculation as graphic. Or should I use the string output and parse it?

**Comment by lebigot** [comment]
With Matplotlib, you would simply pass the nominal values and uncertainties separately, and they can be obtained directly (for both [scalars](https://pythonhosted.org/uncertainties/user_guide.html#access-to-the-uncertainty-and-to-the-nominal-value) and [arrays](https://pythonhosted.org/uncertainties/numpy_guide.html#uncertainties-and-nominal-values)). 

All the answers to your questions so far are in the [documentation](https://pythonhosted.org/uncertainties/index.html#available-documentation) , so I encourage you to have a look or search there. 😀
