### ISSUE TITLE
Question: can np.nan stand in for nan+/-0?

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [lebigot/uncertainties#169]
I'm trying to use uncertainties with Pandas, Pint and Pint-Pandas.  Pint-Pandas makes it easy to have quantified values on a column basis that really don't interact much (or at least badly) with other columns.

uncertainties relies of wrappers to do its things, whereas Pint and Pint-Pandas are now very complete in using ExtensionArrays to interact with Pandas.  ExtensionArrays define a value for their na_type, which for most things numeric means np.nan.

In my past dealings with uncertainties, the nan for that has been nan+/-0, which has been fine, except that it now makes for difficult promotion rules.  If I have an extension array of quantities (tons of CO2, millions of USD, whatever) with normal float64 magnitudes, the correct na_value for that is np.nan.  But if I fill the array with uncertainties as magnitudes, the logical na_value would be nan+/-0.  But there's no concept of multiple na_value depending on whether there are uncertainties in the mix.

One solution is to just bite the bullet and say "if you use uncertainties anywhere, then every dataframe needs to honor them, meaning that the na_value for ANYTHING is nan+/-0 (and all magnitudes must promote to UFloat)."  What I'd like to do is to manage that column-by-column.

Is there a world in which np.nan is a fully adequate value for uncertainties, with whatever promotions/substitutions, etc happening within the wrappers?  Or do I need to majorly rethink my approach of layering these various abstractions (uncertainties, quantities, DataFrames) together?

**Comment by lebigot** [comment]
Thanks for the interesting details.

Now, can you show an example of what you want to do? I'm not fully seeing the problem yet (in part because uncertainties automatically promotes NaN to NaN±0).

**Comment by MichaelTiemannOSC** [comment]
Here is some sample code.  It does not play well with the current version of pint-pandas 0.3, but I have a pull-request that does make it work (https://github.com/hgrecco/pint-pandas/pull/140).  My latest iteration doesn't show the problems I think will exist due to having multiple `na_value`s, but the extra things the code does to smooth things over feels fragile.

```
import numpy as np
import uncertainties as un
from uncertainties import unumpy as unp
import pandas as pd
import pint
import pint_pandas

from pint import Quantity as Q_
from pint_pandas import PintArray as PA_
from uncertainties import ufloat

pa1 = pd.Series(PA_([1.1, 1.2, np.nan], dtype='pint[m]'))
pa2 = pd.Series(PA_([1.1, 0, 1.3], dtype='pint[m]'))
pa3 = pa1 / pa2
# This is the simple case of pure float64 magnitudes
print(pa3)
print(pd.isna(pa3))

upa1 = pd.Series(PA_([1.1, 1.2, ufloat(np.nan, 0), np.nan], dtype='pint[m]'))
print(upa1)
print(pd.isna(upa1))
upa2 = pd.Series(PA_([ufloat(0.0, 0.0), ufloat(0.0, .1), ufloat(0.0, .2), ufloat(0.0, .3)], dtype='pint[m]'))
upa3 = pd.concat([upa1,upa2])
print(upa2)
print(upa3)
print(pd.isna(upa3))
```
