### ISSUE TITLE
FFT support for uncertainties package

### ISSUE THREAD

**Issue by TimVog** [lebigot/uncertainties#172]
First, thanks for the nice program.

It is already a great help to keep track of uncertainties for, in principle, simple but tedious calculation.

For my concrete measurement problem: I recorded multiple time traces (Voltage vs. time) of the same signal, a pulse on a noisy background. Taking the mean and standard deviation is easy because they are all defined over the same time axis.

Unfortunately, the rest of my analysis needs to be done in frequency domain, and I saw that the FFT support is planned for in the future. Is there already a timeline when this could be expected?

My current approach (but I'm not certain if that is the right way), to do an np.fft.rfft of each time trace, where I'm interested in the magnitude. Of all these magnitudes, I take the standard deviation at each frequency.

This approach has two possible problems:
1. Averaging the traces in time domain leads to a lower noise floor in frequency domain. When I do an FFT of each single trace, the bandwidth of my signal is limited because each trace by itself has a higher noise floor.

2. I'm not only interested in the magnitude, but I have another measurement set, where I later want to take the division of both Fourier-transformed datasets. This will give me the complex transmission coefficient (which I can take the magnitude of). I'm currently not sure how uncertainties in the time domain propagate to the complex numbers in frequency domain, in particular if I first divide two different datasets (both with uncertainties) and take then the magnitude.

Do you have any idea how the uncertainties can be tracked in the case of a real-input discrete Fourier transformation?

**Comment by lebigot** [comment]
Thank you for your feedback.

I will unfortunately not add FFT support in the foreseeable future.

If I understand correctly, you would like to have uncertainties in your Fourrier transforms (or on statistics over them). I would suggest you do sine and cosine Fourier transforms "manually" without an FFT. It's not hard (for example with NumPy), but it's much slower that using an FFT. `uncertainties` will give you the uncertainties on the Fourier coefficients, etc.

Note that complex numbers with uncertainties are not supported (but could be, in principle), so you would obtain the sine and cosine transforms separately.

Does this answer your need?

**Comment by lebigot** [comment]
PS: this would be better as a Discussion, not an issue, as FFT is not a supported feature of `uncertainties`, so I'll close this "issue" when our conversation is over.

**Comment by TimVog** [comment]
Thank you for your answer and insight. The way of doing a classic FFT with sin/cos and using `uncertainties` seems to be viable, I will soon try it out. 

And sorry for placing this as an issue, I was not aware of the Discussion section. If you want, you can already close this issue here and I can write an update in the discussion section, if I was successful.
