### ISSUE TITLE
Missing covariance values expected

### ISSUE THREAD

**Issue by srkunze** [lebigot/uncertainties#173]
Considering this script

```
import uncertainties
from uncertainties import ufloat
from uncertainties.umath import sin

scanner_b = ufloat(0, 0.1, 'scanner_b')
scanner_h = ufloat(20, 0.1, 'scanner_h')

stage_x = ufloat(0, 0.1, 'stage_x')
spot_x = scanner_h * sin(scanner_b)

work_x = stage_x + spot_x

covs = uncertainties.covariance_matrix([scanner_b, scanner_h, spot_x, stage_x, work_x])
for cs in covs:
    print(' '.join(f'{c:4.2f}' if c else '    ' for c in cs))
```

Why is the output the following?
```
0.01      0.20      0.20
     0.01               
0.20      4.00      4.00
               0.01 0.01
0.20      4.00 0.01 4.01
```

I would have expected `scanner_h` to influence `work_x`.

Is it related to second-order errors as being described here: https://uncertainties-python-package.readthedocs.io/en/latest/tech_guide.html#linear-propagation-of-uncertainties

**Comment by lebigot** [comment]
This zero covariance between `scanner_h` and `work_x` actually comes from the fact that the average <sin(`scanner_b`)> is 0, in the linear approximation used by `uncertainties`. Even without this approximation, any symmetric probability distribution for `scanner_b` (Gaussian…) yields exactly 0 for this average, and therefore a 0 covariance.

This <sin(`scanner_b`)> appears directly if you write down the formula for the covariance of `scanner_h` and `work_x`: you get `0.2*<sin(scanner_b>`. I haven't checked this numerically, but this could in principle be done by using a distribution for `scanner_b` which has 0 mean and is asymmetrical.

**Comment by lebigot** [comment]
This zero covariance between `scanner_h` and `work_x` actually comes from the fact that the average <sin(`scanner_b`)> is 0, in the linear approximation used by `uncertainties`. Even without this approximation, any symmetric probability distribution for `scanner_b` (Gaussian…) yields exactly 0 for this average, and therefore a 0 covariance.

This <sin(`scanner_b`)> appears directly if you write down the formula for the covariance of `scanner_h` and `work_x`: you get `0.2*<sin(scanner_b>`. I haven't checked this numerically, but this could in principle be done by using a distribution for `scanner_b` which has 0 mean and is asymmetrical.
