### ISSUE TITLE
Wrong uncertainty when calculating with ufloat variables

### ISSUE THREAD

**Issue by hb9ezs** [lebigot/uncertainties#175]
When running the following code:
```
c = 3.0
x = ufloat(1, 0.5)
y = ufloat(c*x.n, c*x.s)
z = c * x

print(f"{x = }")    
print(f"{y = }")    
print(f"{z = }")    
print()
print(f"{y/x = }")
print(f"{z/x = }")
```
I get the following output:
```
x = 1.0+/-0.5
y = 3.0+/-1.5
z = 3.0+/-1.5

y/x = 3.0+/-2.12 # expected result
z/x = 3.0+/-0    # correct nominal value, wrong uncertainty
```

When calculating z/x I get the wrong uncertainty, but the correct nominal value.
I assume there is a problem with the variable assignment, because running `z = c * copy.copy(x)` gives the correct result.

**Comment by lebigot** [comment]
`uncertainties` is correct, here (as it has been for nearly 15 years, so major calculation bugs are now very unlikely): z/x = c, right? And c is *exactly* equal to 3.
