### ISSUE TITLE
TypeError: can't convert an affine function (<class 'uncertainties.core.AffineScalarFunc'>) to float; use x.nominal_value

### ISSUE THREAD

**Issue by priyankaboora** [lebigot/uncertainties#176]
Hi,
This is my code below, I want to calculate the square root of (x - y) with uncertainty in x and y. But I am facing the error of "**TypeError: can't convert an affine function (<class 'uncertainties.core.AffineScalarFunc'>) to float; use x.nominal_value".**
Can you please suggest to me what should I change in code.
##########################################################
from uncertainties import ufloat
import math
from uncertainties.umath import *
x = ufloat(136.00, 19)
y = ufloat(4.46, 0)
z = (math.sqrt(x - y))
print(z)
################################################################

**Comment by lebigot** [comment]
If you have a look at the [User Guide](https://uncertainties.readthedocs.io/en/latest/user_guide.html#mathematical-operations), you can see that mathematical functions must come from the `umath` module:
```python
…
from uncertainties.umath import sqrt
…
z = sqrt(x-y)
```

**Comment by priyankaboora** [comment]
Thank you
