### ISSUE TITLE
intersphinx mapping to uncertainties doesn't work

### ISSUE THREAD

**Issue by cdeil** [lebigot/uncertainties#28]
I have a Python package `gammapy` that is using the [intersphinx_mapping](http://sphinx-doc.org/ext/intersphinx.html) sphinx extension to create-cross links e.g. to the `numpy`, `scipy`, `astropy`, ... docs.

For some reason the links to `uncertainties` don't work, even though I've added `http://pythonhosted.org/uncertainties/` to the `intersphinx_mapping` dict and the file `http://pythonhosted.org/uncertainties/objects.inv` does exist and is successfullly downloaded by sphinx. I think the problem is that the file doesn't contain the usual information, because it is too small (532 bytes).

@lebigot In case you have no idea what I'm talking about ... [here](https://gammapy.readthedocs.org/en/latest/api/gammapy.image.binary_opening_circle.html?highlight=scipy) is an example where linking against the `scipy` docs worked and [here](https://gammapy.readthedocs.org/en/latest/api/gammapy.morphology.gaussian_sum_moments.html) is an example where linking against the `uncertainties` docs doesn't work.

Any idea how to fix this?

(I'm trying to fix this on my end at https://github.com/gammapy/gammapy/pull/83 )

**Comment by lebigot** [comment]
While autodocs is an interesting option, I am closing this issue. In fact, I prefer giving users the current, manually curated online documentation along with text-only docstrings that they can more easily read in a shell (compared to giving them an automatically generated documentation: for users, a custom documentation is nicer than an automatic one, and having non-trivial ReST markups when reading pure text in a shell is not so convenient).
