### ISSUE TITLE
`nominal_value(x)` on array

### ISSUE THREAD

**Issue by mtrbean** [lebigot/uncertainties#32]
What is the best way to construct a correlated array of values while having an easy way to extract nominal_value and std_dev? I wanted to get the nominal values of an array, but `uncertainties.nominal_value` doesn't work on a regular numpy array. I could construct a `uarray` by looping through all values and use the `nominal_value` attribute of `uarray`, but that doesn't sound optimal.

```
In [379]: x = uncertainties.correlated_values([0,1], np.eye(2)), x
Out[379]: (0.0+/-1.0, 1.0+/-1.0)

In [381]: uncertainties.nominal_value(np.array(x))
Out[381]: array([0.0+/-1.0, 1.0+/-1.0], dtype=object)

In [382]: uncertainties.unumpy.uarray(x)
-c:1: UserWarning: Obsolete: uarray() should now be called with two arguments. Code can be automatically updated with python -m uncertainties.1to2 -w ProgramDirectory.
TypeError: can't convert an affine function (<class 'uncertainties.AffineScalarFunc'>) to float; use x.nominal_value
```

**Comment by lebigot** [comment]
Your ``np.array(x)`` is correct:
```
>>> numpy.array(x)
array([0.0+/-1.0, 1.0+/-1.0], dtype=object)
```

In order to get the nominal values of an array, you need to use the array-aware function:
```
>>> unumpy.nominal_values(np.array(x))                                          
array([ 0.,  1.])
```
You will notice the plural *values* (instead of the singular *value* from ``uncertainty.nominal_value()``).

**Comment by mtrbean** [comment]
Oh sorry I overlooked the `unumpy.nominal_values` function in the documentation. Thanks for the great library!

**Comment by lebigot** [comment]
No problem. :) I am glad that you find the uncertainties package useful.

**Comment by INgauriS** [comment]
> Your `np.array(x)` is correct:
> 
> ```
> >>> np.array(x)
> array([0.0+/-1.0, 1.0+/-1.0], dtype=object)
> ```
> 
> Reference: http://pythonhosted.org/uncertainties/numpy_guide.html#arrays
> 
> In order to get the nominal values of an array, you need to use the array-aware function:
> 
> ```
> >>> from uncertainties import unumpy
> >>> unumpy.nominal_values(np.array(x))                                          
> array([ 0.,  1.])
> ```
> 
> You will notice the plural _values_ (instead of the singular _value_ from `uncertainty.nominal_value()`).
> Reference: http://pythonhosted.org/uncertainties/numpy_guide.html#uncertainties-and-nominal-values
> 
> Now, it may be a good idea to only have a single function `uncertainty.nominal_value()` that works on arrays too. This has the disadvantage that it would be different in spirit from things like `numpy.sin()`, etc., where array-specific functions are put in the array-handling module. On the other hand, a single function is easier to remember, and would be a bit like Python's `len()`, which works on many types. I am not yet sure whether any change is needed.

Hello Lebigot, I have recently started using the uncertainty package.  I didn't find much any problem in using it except the USER WARNING, (UserWarning: Obsolete: uarray() should now be called with two arguments. Code can be automatically updated with python -m uncertainties.1to2 -w ProgramDirectory.), Could you please let me know how can I get rid-off this warning. Thank you in advance (hope you can answer)

**Comment by lebigot** [comment]
If you are calling `uarray()`, the message instructs you to call it with two arguments. The built-in help on this function tells you how to use it correctly.
If something is still not clear, let me know what it is.

**Comment by INgauriS** [comment]
> If you are calling `uarray()`, the message instructs you to call it with two arguments. The built-in help on this function tells you how to use it correctly.
> If something is still not clear, let me know what it is.

But I am giving two arguments in uarray, e.g., unumpy.uarray((Lum, abs(Lum_err))), but still it is giving me the same warning. I am afraid if later this warning will arise error in computation .

**Comment by lebigot** [comment]
You are actually giving one argument (a tuple). You need to remove one set of parentheses.

**Comment by INgauriS** [comment]
> You are actually giving one argument (a tuple). You need to remove one set of parentheses.

aaha, sorry, I just copied from one of your blog and didn't look it carefully. Thank you for your help!

**Comment by lebigot** [comment]
Good. This must be a very old blog post (written by someone else, as I unfortunately haven't written any post yet!).
