### ISSUE TITLE
Weird behaviour doing repeated calculations

### ISSUE THREAD

**Issue by bilderbuchi** [lebigot/uncertainties#37]
Hi!
I found something very weird (a bug? user error?) when doing calculations for a number of ufloats in a list. Running this script
```
from uncertainties import ufloat
import uncertainties.umath as um

k = ufloat(0.245548, 0.003834, 'spring constant')
r = ufloat(0.29, 0.001, 'distance')
alpha = ufloat(0,um.radians(1.0), 'angle')

deflection_list = [ufloat(0.0, 1e-6, 'deflection distance'),
                   ufloat(0.855e-3, 1e-6, 'deflection distance')]

for x in deflection_list:
    theta = x/r
    F = k * theta / (r * um.cos(alpha))
    print('Deflection x={:.2f} um\nF={:.2f} uN'.format(1e6*x, 1e6*F))
    print('Error components:')
    for k, v in F.error_components().items():
        print(k.tag, v)
    print('\n')
```
repeatedly gives different results for `F` for the second item in `deflection_list`. The first item (deflection 0) always stays constant. The problem disappears as soon as there is only one entry in `deflection_list`.

One run prints

```
Deflection x=0.00+/-1.00 um
F=0.00+/-2.92 uN
Error components:
spring constant 0.0
deflection distance 2.919714625445898e-06
distance 0.0
angle 0.0


Deflection x=855.00+/-1.00 um
F=0.00+/-177.44 uN
Error components:
angle 0.00017743834844888845
distance 0.0
deflection distance 0.0
```
(which is incorrect, the second F should not have an expected value of 0).
Running the script again gives
```
Deflection x=0.00+/-1.00 um
F=0.00+/-2.92 uN
Error components:
spring constant 0.0
angle 0.0
deflection distance 2.919714625445898e-06
distance 0.0


Deflection x=855.00+/-1.00 um
F=2948.28+/-10.74 uN
Error components:
distance 1.0166468489892985e-05
angle 0.0
deflection distance 3.4482758620689654e-06
```
(now we get a value for the second `F`, but why is the script behaviour not deterministic?!?)

Additionally, on some runs the error contribution for the deflection distance occurs twice for an unknown reason, the computation didn't change!: 
```
Deflection x=0.00+/-1.00 um
F=0.00+/-2.92 uN
Error components:
spring constant 0.0
angle 0.0
distance 0.0
deflection distance 2.919714625445898e-06


Deflection x=855.00+/-1.00 um
F=0.00+/-0.01 uN
Error components:
deflection distance 1.0166468489892985e-08
deflection distance 0.0
distance 0.0
angle 0.0
```

Any idea what's going wrong here?
This is on Python 3.5.1, Anaconda 2.4.0 (64-bit), uncertainties 2.4.7.1 installed with pip.

**Comment by bilderbuchi** [comment]
Erm, how embarassing. :disappointed: The use of single-letter variable names did me in - I rewrote my ufloat `k` when going through the error component list with `for k, v in ...`.
Sorry for the noise, closing this.

**Comment by lebigot** [comment]
No problem. I am glad that `uncertainties` is working for you. :)
