### ISSUE TITLE
working with units?

### ISSUE THREAD

**Issue by gracca** [lebigot/uncertainties#43]
I would like to work with units, for example:

```python
>>> import astropy.units as u
>>> from uncertainties import ufloat
>>> d = ufloat(211, 55) * u.pc
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-c62b18eb7db0> in <module>()
----> 1 d = ufloat(211, 55) * u.pc

TypeError: unsupported operand type(s) for *: 'Variable' and 'Unit'
```

Is there another way to use units with the uncertainties package?

**Comment by lebigot** [comment]
The [Pint units package](http://python-in-the-lab.blogspot.fr/2014/05/pint-05-now-with-uncertainties.html) is compatible with the `uncertainties` package. Would it suit you?

**Comment by gracca** [comment]
Didn't know about Pint, going to try it! Thank you very much, keep up the good work!

**Comment by lebigot** [comment]
PS: Note that [Astropy does not perform correct calculations in all cases](https://pint.readthedocs.org/en/0.7.2/): it ignores correlations (x-x should be exactly zero, for instance, but is probably not zero in Astropy).
