### ISSUE TITLE
Printing test fails for Python 2.6.

### ISSUE THREAD

**Issue by lebigot** [lebigot/uncertainties#45]
One unit test fails for Python 2.6: in test_uncertainties.py:

Incorrect representation '-000000000.0inf(inf)' for format '020S' of -inf+/-inf: '-00000000000inf(inf)' expected.

This works for Python 2.7.

**Comment by bilderbuchi** [comment]
maybe consider dropping 2.6 support? see also hgrecco/pint#358

**Comment by lebigot** [comment]
I made the effort of supporting versions starting from Python 2.3, so it's easy to keep support for Python 2.6 and help those of us who are stuck with Python installations that they have little control over. :)

**Comment by lebigot** [comment]
The original test fail comes from the fact that Python 2.6 and 2.7 do not give the same result for `format(float("inf"), '015')`:
- Python 2.7: `'000000000000inf'`
- Python 2.6: `'0000000000.0inf'`

The observed behavior is thus "normal" and the unit test should not give the same result for all versions of Python.

**Comment by lebigot** [comment]
Fixed in revision 3121d69.

The original Python 2.6 behavior (with a none formatting type, like here) is preserved (even though the result would look better with the theoretically equivalent g formatting type, the g formatting type is not, in practice, equivalent to the none type, so I decide to follow the official—if flawed—behavior).
