### ISSUE TITLE
Initialising empy array

### ISSUE THREAD

**Issue by pjacob2** [lebigot/uncertainties#55]
I have found it that I quite often want to initiliase an empty array. If I simply initiliase an empty array or an array of zeros an exception will be thrown once I try to assign `ufloat` values to it. Would it be worthwhile to include a little routine to automatically do this? This is what I am currently using (probably not the most efficient version but it works):

    def unctarray(a,b):
        i=0
        temp = np.array([])
        while i<a*b:
            temp=np.append(temp,np.array([unct.ufloat(0,0)]))
            i+=1
        array = np.reshape(temp,(a,b))
        return(array)

**Comment by lebigot** [comment]
The function that you are listing can be directly written for an arbitrary array shape as:

```python
def unctarray(*shape):
    "Return a NumPy array of the given shape, filled with zeros."
    return unumpy.uarray(numpy.zeros(shape), numpy.zeros(shape))
```

This uses the usual ``unumpy.uarray()`` array creation function in a quite straightforward way, so I do not feel the need to add any specific function for this particular case.

If you want an array which is really more "empty" (non initialized), you can replace ``numpy.zeros()`` with ``numpy.empty()``, which is generally faster (for bigger arrays).

Now, if you really want an empty array (with no element) that can contain numbers with uncertainty, the normal way of doing it would be ``unumpy.uarray([], [])``, which gives the same result as ``numpy.array([], dtype=object)``.

For more information about uncertainties in arrays: http://pythonhosted.org/uncertainties/numpy_guide.html.

I hope this helps!
