### ISSUE TITLE
Support for mean in pandas DataFrame of ufloat

### ISSUE THREAD

**Issue by bgatessucks** [lebigot/uncertainties#58]
Background: 
I would like to use the uncertainties package to hold and manipulate the results of Monte Carlo simulations. 
At a high level I find a pandas DataFrame to be the most convenient structure, therefore I tried to combine the two packages as in the simple example below.

Is there a way I can already apply `mean` to different slices of the DataFrame ?
If not, would you please consider adding support for it ?

```python
import pandas as pd
import numpy as np

import uncertainties
from uncertainties import unumpy

value = pd.DataFrame(np.arange(12).reshape(3, 4), index=['r1', 'r2', 'r3'], columns=['c1', 'c2', 'c3', 'c4'])
err = pd.DataFrame(0.01 * np.arange(12).reshape(3, 4) + 0.005, index=['r1', 'r2', 'r3'], columns=['c1', 'c2', 'c3', 'c4'])

df = pd.DataFrame(unumpy.uarray(value.values, err.values), 
                                index=['r1', 'r2', 'r3'], 
                                columns=['c1', 'c2', 'c3', 'c4'])

df.sum(axis=0)  # This works
df.sum(axis=1)  # This works
df.loc[['r1', 'r3'], :].sum(axis=1)  # This works
df.iloc[0:2, 1:].sum(axis=1)  # This works

df.mean(axis=0)  # This does not work: it can be fudged with: df.apply(lambda x: x.sum() / x.shape[0])
df.mean(axis=1)  # This does not work: it can be fudged with: df.T.apply(lambda x: x.sum() / x.shape[0])
df.loc[['r1', 'r3'], :].mean(axis=1)  # This does not work
```

**Comment by lebigot** [comment]
What are the error messages?

**Comment by bgatessucks** [comment]
```python
df.mean(axis=0)
```
`Series([], dtype: float64)`


```python
df.mean(axis=1)
```
```python
r1   NaN
r2   NaN
r3   NaN
dtype: float64
```

**Comment by lebigot** [comment]
Pandas seems to get the data type wrong.

I don't see how the uncertainties module could affect Pandas on this issue.

I would suggest that you cross-post the issue in Pandas itself. If you do, can you post a link to it here?

**Comment by bgatessucks** [comment]
Done:
bgatessucks/pandas#14162

**Comment by lebigot** [comment]
"Probably a Pandas bug": https://github.com/pydata/pandas/issues/14162#issuecomment-245055691. That's my feeling too, so closing this, as I don't see what can be done within `uncertainties`.
