### ISSUE TITLE
Continious Integration

### ISSUE THREAD

**Issue by rth** [lebigot/uncertainties#61]
Travis-CI was disabled in August for this repo. Should we add it back? The python versions that are tested in `.travis.yml` also might need to be updated.

Also I'm not sure if it would be useful to add CI tests on windows with [AppvVeyor](https://www.appveyor.com/)? In which case I can add the setup file.

**Comment by lebigot** [comment]
Thank you for updating the Travis CI configuration. I will activate Travis back.

It would be useful to also do the tests on Windows as you propose. If you can do a pull request, that's great. I like comments in configuration files too, as they help understand the less obvious parts and update the configuration later if needed. :)
