### ISSUE TITLE
Inconsistency between `min` and `<`

### ISSUE THREAD

**Issue by pjacob2** [lebigot/uncertainties#66]
I have a dictionary, `results`, containing the following values:
```
{'DC_NO': 115439.5272+/-227.5783569,
 'DC_NO_uniform_prior': 128170.5718+/-254.9207861,
 'NDC_NO': 121293.7951+/-67.26122141,
 'Nested_DC_NO': 115361.3262+/-400.9781353,
 'Nested_DC_NO_uniform_prior': 128369.6196+/-804.0209628,
 'Nested_DC_O': 119185.6415+/-0,
 'Nested_NDC_NO': 120300.3604+/-259.6579933,
 'Nested_NDC_O': 133606.5811+/-1661.534633}
```
If I  run `min(results)` I obtain the answer `'DC_NO'`. The nominal value of `'DC_NO'` of course if greater than that of `'Nested_DC_NO'` so I tested `results['DC_NO']<results['Nested_DC_NO']` which returns the answer `False`, thus contradicting the previous result. One might of course argue that the error on `'DC_NO'` is smaller and thus it might be more likely to be smaller than `'Nested_DC_NO'` and therefore `min()` gives me the correct answer but the fact that `<` disagrees with this assessment surprised me. To me it appears that there is an inconsistency in the implementation of `min()` and `<`. What is this caused by? Or is this me making a mistake?

**Comment by lebigot** [comment]
`min(results)` gives you the minimum _key_, which is indeed `CD_NO` (alphabetically).

If you want the key with the minimum value, you need to do something like this `min(results, key=lambda key: results[key])`. This should return `'Nested_DC_NO'`. Please let me know if this works.

**Comment by pjacob2** [comment]
You are right, that was entirely my mistake, my apologies. It does indeed work.
