### ISSUE TITLE
Error calculation in definite integral

### ISSUE THREAD

**Issue by vaidehiratna** [lebigot/uncertainties#68]
Hello,

I am calculating luminosity for a log parabola model using the following code. I want to compute the uncertainties in the output values. Since the code performs a numerical integration, is it possible to use the uncertainties package to get the desired results? I have error measurements in alpha, beta and norm values.

def Gamma_Lumin(alpha,beta,norm,Eb,red_shift,low_energy,high_energy):
        Dl = lumin_dist(red_shift)
        Eb = Eb/1000.           # convert to GeV
        x2 = lambda x: 1.6*norm*(x/(Eb*(1+red_shift)))**(-alpha-(beta*log((x/(Eb*(1+red_shift))),10)))*(1/(1+red_shift)**2)*x   # Equation taken from R. Nemmen et al. 2012
        E,e = integrate.quad(x2, low_energy, high_energy)       # Energy should be in GeV
        Lumin = 4*pi*Dl**2*E
        E = '%.3e' % E
        Lumin = '%.3e' % Lumin
        print 'Log parabolic Gamma-ray Luminosity is %s and energy flux is %s' % (Lumin,E)
        return float(Lumin), float(E)

Thanks.

**Comment by lebigot** [comment]
Have you tried the method indicated in the documentation? Here it is: http://pythonhosted.org/uncertainties/user_guide.html#making-custom-functions-accept-numbers-with-uncertainties
