### ISSUE TITLE
How to run tests using Python 3

### ISSUE THREAD

**Issue by nasfarley88** [lebigot/uncertainties#71]
I'm developing for #70 but I can't figure out how to reliably test using Python 3.6 (my daily driver). 

Is there somewhere in the docs that describes the testing procedure? If not, could this be added?

**Comment by rth** [comment]
You could try runing [`python setup.py nosetests -sv`](https://github.com/lebigot/uncertainties/blob/master/.travis.yml#L24) or `pytest  uncertainties/`

**Comment by lebigot** [comment]
Indeed. Thank you @rth!

Something similar is already included in INSTALL.txt, which I find sufficient.
