### ISSUE TITLE
Can I do matrix convolutions and get uncertainties after the convolution using uncertainties package?

### ISSUE THREAD

**Issue by unknown5493** [lebigot/uncertainties#73]
As the title says. Can I do convolution using scipy or maybe there is an inbuilt uncertainties package to do convolution. Is it possible to do convolution and get uncertainties with a package. or should I write the entire for loop for convolution in python?

**Comment by lebigot** [comment]
I am guessing that your best bet is to use the fact that the uncertainties package handles NumPy arrays, [as indicated in the documentation](http://pythonhosted.org/uncertainties/numpy_guide.html). I would start from there and thus first try solutions without a loop.
