### ISSUE TITLE
Chose right number of significant digits in unumpy arrays printing

### ISSUE THREAD

**Issue by michaels011235** [lebigot/uncertainties#84]
I really like the uncertainties package, especially the feature to chose a reasonable number of significant digits:

> When uncertainties must choose the number of significant digits on the uncertainty, it is defined with the Particle Data Group rounding rules (these rules keep the number of digits small, which is convenient for reading numbers with uncertainties, and at the same time prevent the uncertainty from being displayed with too few digits)

Unfortunately, this does not work with printing unumpy arrays. It would be nice to have this possibility when printing unumpy arrays.

**Comment by lebigot** [comment]
Your friend here is the usual [numpy.set_printoptions()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html). I'm therefore closing this issue. If after trying you don't succeed, feel free to reopen this issue.
