### ISSUE TITLE
A BUG: ufloat_fromstr can't deal with string '0.20+-0.01'

### ISSUE THREAD

**Issue by Ian-Jhon** [lebigot/uncertainties#93]
`>>> from uncertainties import ufloat_fromstr`
`>>> aa = '0.20+/-0.01'`
`>>> bb = '0.20+-0.01'`
`>>> ufloat_fromstr(aa)`
`0.2+/-0.01`
`>>> ufloat_fromstr(bb)`
`ValueError: Cannot parse 0.20+-0.01: see the documentation for ufloat_fromstr() for a list of accepted formats`

**Comment by lebigot** [comment]
What is it that you are looking for exactly? The message you quote indicates that accepted formats are documented (`help(ufloat_fromstr)`), and the one that you try to give is _not_ supposed to work. Is there any compelling reason to also accept it? On reason I see to not accept it is that it is a valid Python expression, with a very different meaning than a number with uncertainty (`0.20+-0.01 == 0.19`).
