### ISSUE TITLE
correlation_matrix() could have values with 0 standard deviation

### ISSUE THREAD

**Issue by lebigot** [lebigot/uncertainties#96]
Currently, `correlation_matrix()` returns NaN values instead of 0 values.

**Comment by adonath** [comment]
Just wanted to note, that this issue seems to break our CI builds (https://travis-ci.org/gammapy/gammapy/jobs/535023286#L3027). I guess I can temporarily restrict the `uncertainties` version to `v3.0.*` for our Travis and Azure builds, but it would be great to have this fixed soon. Thanks!

**Comment by lebigot** [comment]
I believe this is related instead to https://github.com/lebigot/uncertainties/issues/97. Something can be done, I'm sure.

**Comment by lebigot** [comment]
I'm going to have a look.

**Comment by lebigot** [comment]
I'm closing this issue, because it is normal that a correlation be NaN between a 0-variance variable and the other, since we divide by a 0 standard deviation.
